### ISSUE TITLE
dev-exp: LZ section 2: kpt pkg get - why repackage from remote instead of using existing local landing-zone folder

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pubsec-declarative-toolkit#97]
section 2 https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/tree/main/solutions/landing-zone#usage

it is not clear where to pull the kpt fetch (inside the repo? and why are we not using the folder already in the repo?)
Went ahead with the default at the repo root - but why are we not just using the local instead of the remote

```
michael@cloudshell:~/github/GoogleCloudPlatform/pubsec-declarative-toolkit (landing-zone-controller-1z583)$ kpt pkg get https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit.git/solutions/landing-zone landing-zone
Package "landing-zone":
Fetching https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit@main
From https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> origin/main
Adding package "solutions/landing-zone".
Fetched 1 package(s).

for example - both are identical as expected 
michael@cloudshell:~/github/GoogleCloudPlatform/pubsec-declarative-toolkit (landing-zone-controller-1z583)$ ls landing-zone/
cicd-examples  environments  img  Kptfile  README.md  setters.yaml  solution.yaml
michael@cloudshell:~/github/GoogleCloudPlatform/pubsec-declarative-toolkit (landing-zone-controller-1z583)$ ls solutions/landing-zone/
cicd-examples  environments  img  Kptfile  README.md  setters.yaml  solution.yaml
michael@cloudshell:~/github/GoogleCloudPlatform/pubsec-declarative-toolkit (landing-zone-controller-1z583)$ git status
On branch main
Your branch is up to date with 'origin/main'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        landing-zone/
```

**Comment by cartyc** [comment]
We're using `kpt pkg get` in order to allow for more of a `apt` or `yum` like experience. In the case of the landing zone the user should be able to run `kpt pkg get https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit.git/solutions/landing-zone` and get the LZ resources without having to use git. 

The upside to this model is we don't need `git` knowledge and updating these `pkg` users can run `kpt pkg update` in order to pull in the latest changes and it abstracts away `git` to some extent. This also lets users just target the solution they need and not have to worry about grabbing more than they need.

Packages should be pulled into the directory of the users choice, in your example you pull the landing zone solution in the `landing-zone` folder.

Nearly forgot, `kpt pkg get` should only be used for deployment. If you are working up maintaining the package or packages you should fork and clone the repo do your work push back to your branch and `kpt pkg get` to test the deployment. 

Here's the official docs on `kpt` packages https://kpt.dev/book/02-concepts/01-packages.

**Comment by cartyc** [comment]
Git users should follow the same pattern. Running `kpt fn render` on local files adds annotations to the target files which sometimes leads to merge conflicts down the road if they get merged into upstream. That's on me for not documenting it better and a good point to highlight in a forthcoming contribution guide.

**Comment by cartyc** [comment]
Tracking in #102
